BUILD=$HOME/repos/git/blender.org/blender/build

CFGDIR=$HOME/tmp/.blender

BLENDER_USER_CONFIG=$CFGDIR
BLENDER_USER_SCRIPTS=$CFGDIR
BLENDER_SYSTEM_SCRIPTS=$CFGDIR
BLENDER_USER_DATAFILES=$CFGDIR
BLENDER_SYSTEM_PYTHON==$CFGDIR

LD_LIBRARY_PATH=$BUILD/lib

gdb $BUILD/bin/blender